# This is a basic workflow to help you get started with Actions

name: tp2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ tp2, testunitaire ]
  pull_request:
    branches: [ tp2, testunitaire ]
    paths:
      - 'test/in.txt'
      - 'test/in2.dat'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
      - name: Setup workspace
        run: |
          wget https://github.com/guyfrancoeur/INF3135_A2020/raw/master/tp/tp1.zip -P ./data
          cd data; unzip tp1.zip -d ../;rm tp1.zip
          

      # Runs a set of commands using the runners shell
      - name: Compilation
        run: |
          gcc -Wall -Werror=vla -pedantic -std=c11 -I/usr/include/CUnit -L/usr/lib/x86_64-linux-gnu -o tp2 tp2.c tcv.o malib.h malib.c -lm
          gcc -Wall -Werror=vla -pedantic -std=c11 -I/usr/include/CUnit -L/usr/lib/x86_64-linux-gnu -o tp1 tp1.c tcv.o -lcunit
       # Runs a set of commands using the runners shell
      - name: test tp2
        run: |
          cat test/in.txt | ./tp2 > out.txt
          cat test/in2.dat | ./tp2
          echo -e "version #: 0.1.10005\n10 0 1000 3\n14 17599 1929292 3.4\n14 19012 1929298 0.1\n15 19511 1000 1929292 1929298\n21 38.2 -10.2 157\n22 0 0 0\n23 0 0 0" > result.txt
          
      - name: Differences
        run: diff out.txt result.txt
